feat(Input): add color picker sub component
Salable/gds pull request #264
Opened 2023-03-22 18:09 UTC by joshokoro

2023-03-23 07:19 UTC, adaptaconer commented on .prettierrc
> +  "trailingComma": "es5",
Can we align this `.prettierrc` file to match the central config we now have? I've created a PR to add it to the GDS so it should be just a copy-and-paste job.

[PR here.](https://github.com/Salable/gds/pull/263)

2023-03-23 07:21 UTC, adaptaconer commented on .eslintrc.json
> +        "@typescript-eslint/await-thenable": "off"
Is there a reason we're disabling this rule instead of resolving its errors? 

Only because all the other repos have this rule enabled so want to avoid creating differences were possible.

If it's not possible to work around the issues and is just a couple of instances I'd rather use `// eslint-disable-next-line @typescript-eslint/await-thenable` instead of disabling the rule globally.

Happy to help out on this one if you have any questions.

2023-03-23 07:25 UTC, adaptaconer commented on src/molecules/input/styled.components.tsx
> +    width: '1.6rem',
Can we switch out these `rem` units for our `measurements` value from the `useTheme()`. You can see an example of this in the other components in this file.

Also, something to note is that the GDS works on a base `px` size of `16px` instead of `10px` as it was in the UI Library. So, if the intention is to have `16px` here then you'll need to use `1 rem` or `measurements[4]`. 

You can [see a breakdown of the measurement sizes here.](https://gds.salable.app/?path=/story/utilities-measurements--default)

2023-03-23 07:27 UTC, adaptaconer commented on src/molecules/input/types.ts
> +export interface IColorPicker {
Can we extend the type with our `GenericProps` type as per the above types. This type adds in things like `className` and our `isStyled` prop to remove the styling on items for testing purposes.

2023-03-23 07:28 UTC, adaptaconer commented on src/molecules/input/styled.components.tsx
> +export const StyledColorPicker = styled.input(() => {
Can we add the `isStyled` prop to this component as well as were it's used in the main `input.tsx` file to align it with the other components in the GDS

2023-03-23 07:29 UTC, adaptaconer requested changes
Left some comments above, nothing major, just to help align it with the GDS and keep them all in sync with each other style and syntax-wise.

Any questions just ping me. 😄

2023-03-23 08:54 UTC, adaptaconer commented on .prettierrc
> +  "trailingComma": "es5",
I've now merged in #263 so you should just need to pull in `main` and run the lint command again locally.

2023-03-29 13:49 UTC, adaptaconer commented on src/molecules/input/input.tsx
> +        placeholder="#000000"
Can we update this to use `colors('black')` to make sure we use the theme colors and items were possible.

2023-03-29 13:51 UTC, adaptaconer commented on src/molecules/input/styled.components.tsx
> +      border: `${measurements['0.25']} solid rgba(0, 0, 0, 0.3)`,
This can be updated to the new `colors()` function as it now supports opacity. So, this can become `colors('black', 30)` which will output this same `rgba()` function.

2023-03-29 13:52 UTC, adaptaconer commented on src/molecules/input/styled.components.tsx
> +      padding: 0,
Can we update to `measurements[0]` so we keep using in-built measurements

2023-03-29 13:53 UTC, adaptaconer commented on .prettierrc
> +{
This file won't be required anymore as we already have a  `.prettierrc.json` file in `main` with the same configuration in so this can be deleted.

2023-03-29 13:55 UTC, adaptaconer commented on src/molecules/input/input.tsx
> +  const regTest = /^#([0-9a-f]{6}){1,2}$/i;
Can we add a comment above this regex just to explain what it does and give an example of what we're looking to achieve with it just so it's clear to us in the future.

2023-03-29 13:56 UTC, adaptaconer commented on src/molecules/input/styled.components.tsx
> +    '::-webkit-color-swatch': {
Will this selector work in other browsers besides Firefox? [Looking at MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-color-swatch) it's only supported in FF and FF dev, could this cause issues?

2023-03-29 13:58 UTC, adaptaconer commented on yarn.lock
>      regenerator-runtime "^0.13.7"
Can we remove this file as we have migrated from `yarn` to `npm` as a part the ticket #200. This has already been completed on `main` so just need to update this PR.

2023-03-29 14:07 UTC, adaptaconer commented on src/molecules/input/__tests__/input.stories.tsx
> +  await expect(colorPickerInput).toHaveValue('#6A6AFB');
Is there a particular reason we're adding the tests via storybook instead of adding them in a dedicated jest test file inside the `__tests__` folder? 

At the moment all the components in the GDS do the tests via a jest file so I'm thinking it might be better to move the tests there to continue with the established workflows we have already. Also, I don't believe the storybook tests will get triggered in the pre-push hook and CI pipeline so might be better to use jest anyway?

This will also resolve the eslint rule disabling at the top of this file because in jest we don't have that issue with the `userEvent` imports/code.

2023-03-29 14:08 UTC, adaptaconer commented on src/molecules/input/__tests__/input.stories.tsx
> +/* eslint-disable @typescript-eslint/await-thenable */
See comment below for storybook testing.

2023-03-29 14:08 UTC, adaptaconer commented on package.json
> +    "@storybook/jest": "^0.0.10",
If we migrate to using jest testing instead of storybook testing, we probably won't need to add this I imagine.

2023-03-29 14:12 UTC, adaptaconer requested changes
Rerevieved, and left a few more comments. Please don't hate me 😂

2023-03-29 14:13 UTC, adaptaconer commented on src/molecules/input/styled.components.tsx
> +export const StyledWrapper = styled(InputElementWrapper)(() => {
We'll need to add the `isStyled` prop here as well as per the below comment for `StyledColorPicker`

2023-03-30 12:49 UTC, adaptajoe requested changes
I've noticed a few issues - Some may overlap with @adaptaconer's commentary, but I'll sum them up here:

- When the input is in an `error` state, the margins / padding on the color picker looks a bit off; we should probably equalise the margins / padding around that part of the `input`.
- For the parts you've added in `input.tsx`, please add `isStyled={isStyled}`; this allows us to test the raw functionality for accessibility and keeps the component in-line with our other Molecules.
- Change to using a `input.test.tsx` file instead of importing Storybook's Jest package; this helps us blanket-test and to keep our files clean and single-purposed.
- Add a comment on the RegEx in `input.tsx` so we can refer to it later.
- Change instances of raw hexadecimal values (#000000) to use our `colors` theme utility. That way we can keep all the colors across the GDS standardised, and means we only have to edit one place to change them all if need be.
- Add `isStyled` in the `styled.components.tsx` file where Conner has stated.
- Use `measurements` where possible. If a value doesn't match, we go to the nearest neighbour (I.E. If I need `5.5rem`, but the nearest is `5rem (measurements[20])`, or `6rem (measurements[24])`, we'd either consult with Dan, or choose either 5rem or 6rem.
- Test in `Firefox` and `Safari`.
- Remove `yarn.lock`.
- Remove additions to `measurements` file.

If you need help with any of this, please let me know and I can hop on a call with you to get it sorted quickly! 😄 Great work for your first GDS ticket, and a lot of these 'issues' are more GDS-preference-oriented.

2023-04-03 09:44 UTC, adaptaconer commented on src/molecules/input/input.functions.ts
> +    border: `${measurements[0.25]} solid transparent`,
Can we switch the `transparent` for `color('transparent')`

2023-04-03 09:47 UTC, adaptaconer commented on src/theme/foundation/colors/colors.ts
> +const colors = (color: keyof typeof colorValues, opacity = 100, type?: 'rgba' | 'hex') => {
Because the `type` property is optional, can we add a default to it? My suggestion would be to default to `rgba` as that's what the `colors` function should return when passed in a string color such as `blue_7`.

2023-04-03 09:48 UTC, adaptaconer requested changes
Overall looks good to me, just some very minor comments/changes needed then happy to approve. 😄

2023-04-03 12:14 UTC, adaptajoe commented
Just a small bug to mention - although I doubt it'll impact much - but when editing the value of `ColorPicker` through the Storybook arguments, it's possible to remove the `#` prepending the hex value and to _not_ have the input flag an error state.

To replicate, do the following:

1. Load up the `ColorPicker` on Storybook.
2. In the `args` panel, locate the `value` field.
3. Delete the `#` and observe.
4. Alternatively, you can append the following string to your local URL (`&args=value:abc123;`).

Again, I doubt this'll affect anything significantly, but thought it would be good to share nonetheless.

2023-04-03 12:16 UTC, adaptajoe commented on src/molecules/input/types.ts
> +
Please add comments above all the below props; you can find examples in the types above `IColorPickerError` and `IColorPicker` - Just a housekeeping rule, really! 😁

2023-04-03 12:17 UTC, adaptajoe commented
> Overall looks good to me, just some very minor comments/changes needed then happy to approve. 😄

Similarly felt here - LGTM but would like some documentation changes just to tidy up pre-merge 😄 Great job dude! 🎉

2023-04-04 10:06 UTC, adaptajoe approved these changes

2023-04-04 14:23 UTC, merged

2023-04-04 14:28 UTC, adaptaconer commented
:tada: This PR is included in version 1.36.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@salable/gds/v/1.36.0)
- [GitHub release](https://github.com/Salable/gds/releases/tag/v1.36.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: